definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  user.auth:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: admin
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: An example of gin Admin
  license:
    name: MIT
    url: https://github.com/liuvigongzuoshi/go-gin-backend-admin/blob/master/LICENSE
  termsOfService: https://github.com/liuvigongzuoshi/go-gin-backend-admin
  title: Golang Gin API
  version: "1.0"
paths:
  /auth:
    post:
      parameters:
      - description: 登陆授权
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/user.auth'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 登陆授权
      tags:
      - 用户模块
swagger: "2.0"
